kind = "mobile"
previewPath = "/"
title = "Masti Video"
version = "1.0.0"
id = "artifacts/masti-video"
router = "expo-domain"

[[services]]
name = "expo"
ensurePreviewReachable = "/status"
paths = [ "/" ]
localPort = 25468

[services.development]
run = "pnpm --filter @workspace/masti-video run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/masti-video", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/masti-video", "run", "serve" ]

[services.env]
PORT = "25468"
BASE_PATH = "/"
